<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfigSeeder extends Seeder {

    public function run() {

        DB::table('config')->insert([
            ['ConfigName' => 'countryList', 'description' => 'Afghanistan', 'value' => 'AF',],
            ['ConfigName' => 'countryList', 'description' => 'Aland Islands', 'value' => 'AX',],
            ['ConfigName' => 'countryList', 'description' => 'Albania', 'value' => 'AL',],
            ['ConfigName' => 'countryList', 'description' => 'Algeria', 'value' => 'DZ',],
            ['ConfigName' => 'countryList', 'description' => 'American Samoa', 'value' => 'AS',],
            ['ConfigName' => 'countryList', 'description' => 'Andorra', 'value' => 'AD',],
            ['ConfigName' => 'countryList', 'description' => 'Angola', 'value' => 'AO',],
            ['ConfigName' => 'countryList', 'description' => 'Anguilla', 'value' => 'AI',],
            ['ConfigName' => 'countryList', 'description' => 'Antarctica', 'value' => 'AQ',],
            ['ConfigName' => 'countryList', 'description' => 'Antigua and Barbuda', 'value' => 'AG',],
            ['ConfigName' => 'countryList', 'description' => 'Argentina', 'value' => 'AR',],
            ['ConfigName' => 'countryList', 'description' => 'Armenia', 'value' => 'AM',],
            ['ConfigName' => 'countryList', 'description' => 'Aruba', 'value' => 'AW',],
            ['ConfigName' => 'countryList', 'description' => 'Australia', 'value' => 'AU',],
            ['ConfigName' => 'countryList', 'description' => 'Austria', 'value' => 'AT',],
            ['ConfigName' => 'countryList', 'description' => 'Azerbaijan', 'value' => 'AZ',],
            ['ConfigName' => 'countryList', 'description' => 'Bahamas', 'value' => 'BS',],
            ['ConfigName' => 'countryList', 'description' => 'Bahrain', 'value' => 'BH',],
            ['ConfigName' => 'countryList', 'description' => 'Bangladesh', 'value' => 'BD',],
            ['ConfigName' => 'countryList', 'description' => 'Barbados', 'value' => 'BB',],
            ['ConfigName' => 'countryList', 'description' => 'Belarus', 'value' => 'BY',],
            ['ConfigName' => 'countryList', 'description' => 'Belgium', 'value' => 'BE',],
            ['ConfigName' => 'countryList', 'description' => 'Belize', 'value' => 'BZ',],
            ['ConfigName' => 'countryList', 'description' => 'Benin', 'value' => 'BJ',],
            ['ConfigName' => 'countryList', 'description' => 'Bermuda', 'value' => 'BM',],
            ['ConfigName' => 'countryList', 'description' => 'Bhutan', 'value' => 'BT',],
            ['ConfigName' => 'countryList', 'description' => 'Bolivia', 'value' => 'BO',],
            ['ConfigName' => 'countryList', 'description' => 'Bosnia and Herzegovina', 'value' => 'BA',],
            ['ConfigName' => 'countryList', 'description' => 'Botswana', 'value' => 'BW',],
            ['ConfigName' => 'countryList', 'description' => 'Bouvet Island', 'value' => 'BV',],
            ['ConfigName' => 'countryList', 'description' => 'Brazil', 'value' => 'BR',],
            ['ConfigName' => 'countryList', 'description' => 'British Indian Ocean Territory', 'value' => 'IO',],
            ['ConfigName' => 'countryList', 'description' => 'Brunei Darussalam', 'value' => 'BN',],
            ['ConfigName' => 'countryList', 'description' => 'Bulgaria', 'value' => 'BG',],
            ['ConfigName' => 'countryList', 'description' => 'Burkina Faso', 'value' => 'BF',],
            ['ConfigName' => 'countryList', 'description' => 'Burundi', 'value' => 'BI',],
            ['ConfigName' => 'countryList', 'description' => 'Cambodia', 'value' => 'KH',],
            ['ConfigName' => 'countryList', 'description' => 'Cameroon', 'value' => 'CM',],
            ['ConfigName' => 'countryList', 'description' => 'Canada', 'value' => 'CA',],
            ['ConfigName' => 'countryList', 'description' => 'Cape Verde', 'value' => 'CV',],
            ['ConfigName' => 'countryList', 'description' => 'Cayman Islands', 'value' => 'KY',],
            ['ConfigName' => 'countryList', 'description' => 'Central African Republic', 'value' => 'CF',],
            ['ConfigName' => 'countryList', 'description' => 'Chad', 'value' => 'TD',],
            ['ConfigName' => 'countryList', 'description' => 'Chile', 'value' => 'CL',],
            ['ConfigName' => 'countryList', 'description' => 'China', 'value' => 'CN',],
            ['ConfigName' => 'countryList', 'description' => 'Christmas Island', 'value' => 'CX',],
            ['ConfigName' => 'countryList', 'description' => 'Cocos (Keeling) Islands', 'value' => 'CC',],
            ['ConfigName' => 'countryList', 'description' => 'Colombia', 'value' => 'CO',],
            ['ConfigName' => 'countryList', 'description' => 'Comoros', 'value' => 'KM',],
            ['ConfigName' => 'countryList', 'description' => 'Congo', 'value' => 'CG',],
            ['ConfigName' => 'countryList', 'description' => 'Congo, The Democratic Republic of The', 'value' => 'CD',],
            ['ConfigName' => 'countryList', 'description' => 'Cook Islands', 'value' => 'CK',],
            ['ConfigName' => 'countryList', 'description' => 'Costa Rica', 'value' => 'CR',],
            ['ConfigName' => 'countryList', 'description' => 'Cote D\'ivoire', 'value' => 'CI',],
            ['ConfigName' => 'countryList', 'description' => 'Croatia', 'value' => 'HR',],
            ['ConfigName' => 'countryList', 'description' => 'Cuba', 'value' => 'CU',],
            ['ConfigName' => 'countryList', 'description' => 'Cyprus', 'value' => 'CY',],
            ['ConfigName' => 'countryList', 'description' => 'Czech Republic', 'value' => 'CZ',],
            ['ConfigName' => 'countryList', 'description' => 'Denmark', 'value' => 'DK',],
            ['ConfigName' => 'countryList', 'description' => 'Djibouti', 'value' => 'DJ',],
            ['ConfigName' => 'countryList', 'description' => 'Dominica', 'value' => 'DM',],
            ['ConfigName' => 'countryList', 'description' => 'Dominican Republic', 'value' => 'DO',],
            ['ConfigName' => 'countryList', 'description' => 'Ecuador', 'value' => 'EC',],
            ['ConfigName' => 'countryList', 'description' => 'Egypt', 'value' => 'EG',],
            ['ConfigName' => 'countryList', 'description' => 'El Salvador', 'value' => 'SV',],
            ['ConfigName' => 'countryList', 'description' => 'Equatorial Guinea', 'value' => 'GQ',],
            ['ConfigName' => 'countryList', 'description' => 'Eritrea', 'value' => 'ER',],
            ['ConfigName' => 'countryList', 'description' => 'Estonia', 'value' => 'EE',],
            ['ConfigName' => 'countryList', 'description' => 'Ethiopia', 'value' => 'ET',],
            ['ConfigName' => 'countryList', 'description' => 'Falkland Islands (Malvinas)', 'value' => 'FK',],
            ['ConfigName' => 'countryList', 'description' => 'Faroe Islands', 'value' => 'FO',],
            ['ConfigName' => 'countryList', 'description' => 'Fiji', 'value' => 'FJ',],
            ['ConfigName' => 'countryList', 'description' => 'Finland', 'value' => 'FI',],
            ['ConfigName' => 'countryList', 'description' => 'France', 'value' => 'FR',],
            ['ConfigName' => 'countryList', 'description' => 'French Guiana', 'value' => 'GF',],
            ['ConfigName' => 'countryList', 'description' => 'French Polynesia', 'value' => 'PF',],
            ['ConfigName' => 'countryList', 'description' => 'French Southern Territories', 'value' => 'TF',],
            ['ConfigName' => 'countryList', 'description' => 'Gabon', 'value' => 'GA',],
            ['ConfigName' => 'countryList', 'description' => 'Gambia', 'value' => 'GM',],
            ['ConfigName' => 'countryList', 'description' => 'Georgia', 'value' => 'GE',],
            ['ConfigName' => 'countryList', 'description' => 'Germany', 'value' => 'DE',],
            ['ConfigName' => 'countryList', 'description' => 'Ghana', 'value' => 'GH',],
            ['ConfigName' => 'countryList', 'description' => 'Gibraltar', 'value' => 'GI',],
            ['ConfigName' => 'countryList', 'description' => 'Greece', 'value' => 'GR',],
            ['ConfigName' => 'countryList', 'description' => 'Greenland', 'value' => 'GL',],
            ['ConfigName' => 'countryList', 'description' => 'Grenada', 'value' => 'GD',],
            ['ConfigName' => 'countryList', 'description' => 'Guadeloupe', 'value' => 'GP',],
            ['ConfigName' => 'countryList', 'description' => 'Guam', 'value' => 'GU',],
            ['ConfigName' => 'countryList', 'description' => 'Guatemala', 'value' => 'GT',],
            ['ConfigName' => 'countryList', 'description' => 'Guernsey', 'value' => 'GG',],
            ['ConfigName' => 'countryList', 'description' => 'Guinea', 'value' => 'GN',],
            ['ConfigName' => 'countryList', 'description' => 'Guinea-bissau', 'value' => 'GW',],
            ['ConfigName' => 'countryList', 'description' => 'Guyana', 'value' => 'GY',],
            ['ConfigName' => 'countryList', 'description' => 'Haiti', 'value' => 'HT',],
            ['ConfigName' => 'countryList', 'description' => 'Heard Island and Mcdonald Islands', 'value' => 'HM',],
            ['ConfigName' => 'countryList', 'description' => 'Holy See (Vatican City State)', 'value' => 'VA',],
            ['ConfigName' => 'countryList', 'description' => 'Honduras', 'value' => 'HN',],
            ['ConfigName' => 'countryList', 'description' => 'Hong Kong', 'value' => 'HK',],
            ['ConfigName' => 'countryList', 'description' => 'Hungary', 'value' => 'HU',],
            ['ConfigName' => 'countryList', 'description' => 'Iceland', 'value' => 'IS',],
            ['ConfigName' => 'countryList', 'description' => 'India', 'value' => 'IN',],
            ['ConfigName' => 'countryList', 'description' => 'Indonesia', 'value' => 'ID',],
            ['ConfigName' => 'countryList', 'description' => 'Iran, Islamic Republic of', 'value' => 'IR',],
            ['ConfigName' => 'countryList', 'description' => 'Iraq', 'value' => 'IQ',],
            ['ConfigName' => 'countryList', 'description' => 'Ireland', 'value' => 'IE',],
            ['ConfigName' => 'countryList', 'description' => 'Isle of Man', 'value' => 'IM',],
            ['ConfigName' => 'countryList', 'description' => 'Israel', 'value' => 'IL',],
            ['ConfigName' => 'countryList', 'description' => 'Italy', 'value' => 'IT',],
            ['ConfigName' => 'countryList', 'description' => 'Jamaica', 'value' => 'JM',],
            ['ConfigName' => 'countryList', 'description' => 'Japan', 'value' => 'JP',],
            ['ConfigName' => 'countryList', 'description' => 'Jersey', 'value' => 'JE',],
            ['ConfigName' => 'countryList', 'description' => 'Jordan', 'value' => 'JO',],
            ['ConfigName' => 'countryList', 'description' => 'Kazakhstan', 'value' => 'KZ',],
            ['ConfigName' => 'countryList', 'description' => 'Kenya', 'value' => 'KE',],
            ['ConfigName' => 'countryList', 'description' => 'Kiribati', 'value' => 'KI',],
            ['ConfigName' => 'countryList', 'description' => 'Korea, Democratic People\'s Republic of', 'value' => 'KP',],
            ['ConfigName' => 'countryList', 'description' => 'Korea, Republic of', 'value' => 'KR',],
            ['ConfigName' => 'countryList', 'description' => 'Kuwait', 'value' => 'KW',],
            ['ConfigName' => 'countryList', 'description' => 'Kyrgyzstan', 'value' => 'KG',],
            ['ConfigName' => 'countryList', 'description' => 'Lao People\'s Democratic Republic', 'value' => 'LA',],
            ['ConfigName' => 'countryList', 'description' => 'Latvia', 'value' => 'LV',],
            ['ConfigName' => 'countryList', 'description' => 'Lebanon', 'value' => 'LB',],
            ['ConfigName' => 'countryList', 'description' => 'Lesotho', 'value' => 'LS',],
            ['ConfigName' => 'countryList', 'description' => 'Liberia', 'value' => 'LR',],
            ['ConfigName' => 'countryList', 'description' => 'Libyan Arab Jamahiriya', 'value' => 'LY',],
            ['ConfigName' => 'countryList', 'description' => 'Liechtenstein', 'value' => 'LI',],
            ['ConfigName' => 'countryList', 'description' => 'Lithuania', 'value' => 'LT',],
            ['ConfigName' => 'countryList', 'description' => 'Luxembourg', 'value' => 'LU',],
            ['ConfigName' => 'countryList', 'description' => 'Macao', 'value' => 'MO',],
            ['ConfigName' => 'countryList', 'description' => 'Macedonia, The Former Yugoslav Republic of', 'value' => 'MK',],
            ['ConfigName' => 'countryList', 'description' => 'Madagascar', 'value' => 'MG',],
            ['ConfigName' => 'countryList', 'description' => 'Malawi', 'value' => 'MW',],
            ['ConfigName' => 'countryList', 'description' => 'Malaysia', 'value' => 'MY',],
            ['ConfigName' => 'countryList', 'description' => 'Maldives', 'value' => 'MV',],
            ['ConfigName' => 'countryList', 'description' => 'Mali', 'value' => 'ML',],
            ['ConfigName' => 'countryList', 'description' => 'Malta', 'value' => 'MT',],
            ['ConfigName' => 'countryList', 'description' => 'Marshall Islands', 'value' => 'MH',],
            ['ConfigName' => 'countryList', 'description' => 'Martinique', 'value' => 'MQ',],
            ['ConfigName' => 'countryList', 'description' => 'Mauritania', 'value' => 'MR',],
            ['ConfigName' => 'countryList', 'description' => 'Mauritius', 'value' => 'MU',],
            ['ConfigName' => 'countryList', 'description' => 'Mayotte', 'value' => 'YT',],
            ['ConfigName' => 'countryList', 'description' => 'Mexico', 'value' => 'MX',],
            ['ConfigName' => 'countryList', 'description' => 'Micronesia, Federated States of', 'value' => 'FM',],
            ['ConfigName' => 'countryList', 'description' => 'Moldova, Republic of', 'value' => 'MD',],
            ['ConfigName' => 'countryList', 'description' => 'Monaco', 'value' => 'MC',],
            ['ConfigName' => 'countryList', 'description' => 'Mongolia', 'value' => 'MN',],
            ['ConfigName' => 'countryList', 'description' => 'Montenegro', 'value' => 'ME',],
            ['ConfigName' => 'countryList', 'description' => 'Montserrat', 'value' => 'MS',],
            ['ConfigName' => 'countryList', 'description' => 'Morocco', 'value' => 'MA',],
            ['ConfigName' => 'countryList', 'description' => 'Mozambique', 'value' => 'MZ',],
            ['ConfigName' => 'countryList', 'description' => 'Myanmar', 'value' => 'MM',],
            ['ConfigName' => 'countryList', 'description' => 'Namibia', 'value' => 'NA',],
            ['ConfigName' => 'countryList', 'description' => 'Nauru', 'value' => 'NR',],
            ['ConfigName' => 'countryList', 'description' => 'Nepal', 'value' => 'NP',],
            ['ConfigName' => 'countryList', 'description' => 'Netherlands', 'value' => 'NL',],
            ['ConfigName' => 'countryList', 'description' => 'Netherlands Antilles', 'value' => 'AN',],
            ['ConfigName' => 'countryList', 'description' => 'New Caledonia', 'value' => 'NC',],
            ['ConfigName' => 'countryList', 'description' => 'New Zealand', 'value' => 'NZ',],
            ['ConfigName' => 'countryList', 'description' => 'Nicaragua', 'value' => 'NI',],
            ['ConfigName' => 'countryList', 'description' => 'Niger', 'value' => 'NE',],
            ['ConfigName' => 'countryList', 'description' => 'Nigeria', 'value' => 'NG',],
            ['ConfigName' => 'countryList', 'description' => 'Niue', 'value' => 'NU',],
            ['ConfigName' => 'countryList', 'description' => 'Norfolk Island', 'value' => 'NF',],
            ['ConfigName' => 'countryList', 'description' => 'Northern Mariana Islands', 'value' => 'MP',],
            ['ConfigName' => 'countryList', 'description' => 'Norway', 'value' => 'NO',],
            ['ConfigName' => 'countryList', 'description' => 'Oman', 'value' => 'OM',],
            ['ConfigName' => 'countryList', 'description' => 'Pakistan', 'value' => 'PK',],
            ['ConfigName' => 'countryList', 'description' => 'Palau', 'value' => 'PW',],
            ['ConfigName' => 'countryList', 'description' => 'Palestinian Territory, Occupied', 'value' => 'PS',],
            ['ConfigName' => 'countryList', 'description' => 'Panama', 'value' => 'PA',],
            ['ConfigName' => 'countryList', 'description' => 'Papua New Guinea', 'value' => 'PG',],
            ['ConfigName' => 'countryList', 'description' => 'Paraguay', 'value' => 'PY',],
            ['ConfigName' => 'countryList', 'description' => 'Peru', 'value' => 'PE',],
            ['ConfigName' => 'countryList', 'description' => 'Philippines', 'value' => 'PH',],
            ['ConfigName' => 'countryList', 'description' => 'Pitcairn', 'value' => 'PN',],
            ['ConfigName' => 'countryList', 'description' => 'Poland', 'value' => 'PL',],
            ['ConfigName' => 'countryList', 'description' => 'Portugal', 'value' => 'PT',],
            ['ConfigName' => 'countryList', 'description' => 'Puerto Rico', 'value' => 'PR',],
            ['ConfigName' => 'countryList', 'description' => 'Qatar', 'value' => 'QA',],
            ['ConfigName' => 'countryList', 'description' => 'Reunion', 'value' => 'RE',],
            ['ConfigName' => 'countryList', 'description' => 'Romania', 'value' => 'RO',],
            ['ConfigName' => 'countryList', 'description' => 'Russian Federation', 'value' => 'RU',],
            ['ConfigName' => 'countryList', 'description' => 'Rwanda', 'value' => 'RW',],
            ['ConfigName' => 'countryList', 'description' => 'Saint Helena', 'value' => 'SH',],
            ['ConfigName' => 'countryList', 'description' => 'Saint Kitts and Nevis', 'value' => 'KN',],
            ['ConfigName' => 'countryList', 'description' => 'Saint Lucia', 'value' => 'LC',],
            ['ConfigName' => 'countryList', 'description' => 'Saint Pierre and Miquelon', 'value' => 'PM',],
            ['ConfigName' => 'countryList', 'description' => 'Saint Vincent and The Grenadines', 'value' => 'VC',],
            ['ConfigName' => 'countryList', 'description' => 'Samoa', 'value' => 'WS',],
            ['ConfigName' => 'countryList', 'description' => 'San Marino', 'value' => 'SM',],
            ['ConfigName' => 'countryList', 'description' => 'Sao Tome and Principe', 'value' => 'ST',],
            ['ConfigName' => 'countryList', 'description' => 'Saudi Arabia', 'value' => 'SA',],
            ['ConfigName' => 'countryList', 'description' => 'Senegal', 'value' => 'SN',],
            ['ConfigName' => 'countryList', 'description' => 'Serbia', 'value' => 'RS',],
            ['ConfigName' => 'countryList', 'description' => 'Seychelles', 'value' => 'SC',],
            ['ConfigName' => 'countryList', 'description' => 'Sierra Leone', 'value' => 'SL',],
            ['ConfigName' => 'countryList', 'description' => 'Singapore', 'value' => 'SG',],
            ['ConfigName' => 'countryList', 'description' => 'Slovakia', 'value' => 'SK',],
            ['ConfigName' => 'countryList', 'description' => 'Slovenia', 'value' => 'SI',],
            ['ConfigName' => 'countryList', 'description' => 'Solomon Islands', 'value' => 'SB',],
            ['ConfigName' => 'countryList', 'description' => 'Somalia', 'value' => 'SO',],
            ['ConfigName' => 'countryList', 'description' => 'South Africa', 'value' => 'ZA',],
            ['ConfigName' => 'countryList', 'description' => 'South Georgia and The South Sandwich Islands', 'value' => 'GS',],
            ['ConfigName' => 'countryList', 'description' => 'Spain', 'value' => 'ES',],
            ['ConfigName' => 'countryList', 'description' => 'Sri Lanka', 'value' => 'LK',],
            ['ConfigName' => 'countryList', 'description' => 'Sudan', 'value' => 'SD',],
            ['ConfigName' => 'countryList', 'description' => 'Suriname', 'value' => 'SR',],
            ['ConfigName' => 'countryList', 'description' => 'Svalbard and Jan Mayen', 'value' => 'SJ',],
            ['ConfigName' => 'countryList', 'description' => 'Swaziland', 'value' => 'SZ',],
            ['ConfigName' => 'countryList', 'description' => 'Sweden', 'value' => 'SE',],
            ['ConfigName' => 'countryList', 'description' => 'Switzerland', 'value' => 'CH',],
            ['ConfigName' => 'countryList', 'description' => 'Syrian Arab Republic', 'value' => 'SY',],
            ['ConfigName' => 'countryList', 'description' => 'Taiwan, Province of China', 'value' => 'TW',],
            ['ConfigName' => 'countryList', 'description' => 'Tajikistan', 'value' => 'TJ',],
            ['ConfigName' => 'countryList', 'description' => 'Tanzania, United Republic of', 'value' => 'TZ',],
            ['ConfigName' => 'countryList', 'description' => 'Thailand', 'value' => 'TH',],
            ['ConfigName' => 'countryList', 'description' => 'Timor-leste', 'value' => 'TL',],
            ['ConfigName' => 'countryList', 'description' => 'Togo', 'value' => 'TG',],
            ['ConfigName' => 'countryList', 'description' => 'Tokelau', 'value' => 'TK',],
            ['ConfigName' => 'countryList', 'description' => 'Tonga', 'value' => 'TO',],
            ['ConfigName' => 'countryList', 'description' => 'Trinidad and Tobago', 'value' => 'TT',],
            ['ConfigName' => 'countryList', 'description' => 'Tunisia', 'value' => 'TN',],
            ['ConfigName' => 'countryList', 'description' => 'Turkey', 'value' => 'TR',],
            ['ConfigName' => 'countryList', 'description' => 'Turkmenistan', 'value' => 'TM',],
            ['ConfigName' => 'countryList', 'description' => 'Turks and Caicos Islands', 'value' => 'TC',],
            ['ConfigName' => 'countryList', 'description' => 'Tuvalu', 'value' => 'TV',],
            ['ConfigName' => 'countryList', 'description' => 'Uganda', 'value' => 'UG',],
            ['ConfigName' => 'countryList', 'description' => 'Ukraine', 'value' => 'UA',],
            ['ConfigName' => 'countryList', 'description' => 'United Arab Emirates', 'value' => 'AE',],
            ['ConfigName' => 'countryList', 'description' => 'United Kingdom', 'value' => 'GB',],
            ['ConfigName' => 'countryList', 'description' => 'United States', 'value' => 'US',],
            ['ConfigName' => 'countryList', 'description' => 'United States Minor Outlying Islands', 'value' => 'UM',],
            ['ConfigName' => 'countryList', 'description' => 'Uruguay', 'value' => 'UY',],
            ['ConfigName' => 'countryList', 'description' => 'Uzbekistan', 'value' => 'UZ',],
            ['ConfigName' => 'countryList', 'description' => 'Vanuatu', 'value' => 'VU',],
            ['ConfigName' => 'countryList', 'description' => 'Venezuela', 'value' => 'VE',],
            ['ConfigName' => 'countryList', 'description' => 'Vietnam', 'value' => 'VN',],
            ['ConfigName' => 'countryList', 'description' => 'Virgin Islands, British', 'value' => 'VG',],
            ['ConfigName' => 'countryList', 'description' => 'Virgin Islands, U.S.', 'value' => 'VI',],
            ['ConfigName' => 'countryList', 'description' => 'Wallis and Futuna', 'value' => 'WF',],
            ['ConfigName' => 'countryList', 'description' => 'Western Sahara', 'value' => 'EH',],
            ['ConfigName' => 'countryList', 'description' => 'Yemen', 'value' => 'YE',],
            ['ConfigName' => 'countryList', 'description' => 'Zambia', 'value' => 'ZM',],
            ['ConfigName' => 'countryList', 'description' => 'Zimbabwe', 'value' => 'ZW',],


        ]);
    }
}                                                                              
